ngs.Constants = {
    PING_COMMAND: "ping",
    GPIO_COMMAND: "gpio",
    GPIO_PULSE_ACTION: "pulse",
    GPIO_SET_PIN_STATE_ACTION: "set_pin_state",
    GPIO_TOGGLE_PIN_STATE_ACTION: "toggle_pin_state",
    CAMERA_COMMAND: "camera",
    REBOOT_COMMAND: "reboot",
    CAMERA_START_HTTP_STREMING_ACTION: "http_start_streaming",
    CAMERA_START_RTMP_STREAMING_ACTION: "rtmp_start_streaming",
    MPU_COMMAND: "mpu",
    SET_ACCELEROMETER_ON_ACTION: "set_accelerometer_on",
    SET_ACCELEROMETER_OFF_ACTION: "set_accelerometer_off",
    SET_GYRO_ON_ACTION: "set_gyro_on",
    SET_GYRO_OFF_ACTION: "set_gyro_off",
    ENGINE_COMMAND: "engine",
    START_ENGINE_ACTION: "start_engine",
    SET_THROTTLE_ACTION: "set_throttle",
    SET_YAW_ACTION: "set_yaw",
    SET_ROLL_ACTION: "set_roll",
    SET_PITCH_ACTION: "set_pitch",
    CAMERA_STOP_STREAMING_COMMAND: "stop_streaming"
};
